### ISSUE TITLE
Дивний рядок, схоже на баг

### ISSUE THREAD

**Issue by koldovsky** [VladyslavLohynskyi/to-do-list#5]
Ймовірно там має бути порівняння з length === 1

https://github.com/VladyslavLohynskyi/to-do-list/blob/c96a1f3ac8a82c2833793793dd41f25fcdcb0700/src/components/App/index.js#L19

**Comment by VladyslavLohynskyi** [comment]
так там мало бути length але коли переписував на хуки упустив length
